package module.core;

public enum pinName {
	POSITION,AMOUNT,SCROLL,CONST,PRESSED,DISTANCE,P1,P2,REF_P1,REF_P2,ANGLE,IN,OUT,OBEN_LINKS,UNTEN_RECHTS,P,SCALE,DATA,DATA1,DATA0,DATA2,DATA3,DATA4,ID1,ID2,ID3,SELECT,OUT1,OUT2,X,Y, CENTER,RADIUS, HASCENTER,
}
