package de.embots.touchflow.module.core;

public enum PinName {
	PRESTABLE,ROTATE,STABLE,IN1,IN2,LEFT_HAND, RESET, OVERALL_GAIN,RIGHT_HAND, POSITION,AMOUNT,SCROLL,CONST,PRESSED,DISTANCE,P1,P2,REF_P1,REF_P2,ANGLE,IN,OUT,OBEN_LINKS,UNTEN_RECHTS,P,SCALE,DATA,DATA1,DATA0,DATA2,DATA3,DATA4,ID1,ID2,ID3,SELECT,SELECT2,OUT1,OUT2,X,Y, CENTER,RADIUS, HASCENTER,rightwristx,rightwristy,
	 CALIBRATE,leftwristx,
	 leftwristy,
	 corcentre,
	 colcentre,
	 rknee,
	 lknee,
	 sagcentre,
	 comx,
	 headz,
	 trancentre,
	 colycentre,
	 pelvisy,
	 leftwristxIN,
	 leftwristyIN,
	 corcentreIN,
	 colcentreIN,
	 rkneeIN,
	 lkneeIN,
	 sagcentreIN,
	 comxIN,
	 headzIN,
	 trancentreIN,
	 colycentreIN,
	 pelvisyIN,
	 leftwristxOUT,
	 leftwristyOUT,
	 corcentreOUT,
	 colcentreOUT,
	 rkneeOUT,
	 lkneeOUT,
	 sagcentreOUT,
	 comxOUT,
	 headzOUT,
	 trancentreOUT,
	 colycentreOUT,
	 pelvisyOUT,
}
