package de.embots.touchflow.module.core;

public enum PinName {
	PRESTABLE,CLICK, ROTATE,STABLE,IN1,IN2, RESET, OVERALL_GAIN, POSITION,AMOUNT,SCROLL,CONST,PRESSED,DISTANCE,P1,P2,REF_P1,REF_P2,ANGLE,IN,OUT,OBEN_LINKS,UNTEN_RECHTS,P,SCALE,DATA,DATA1,DATA0,DATA2,DATA3,DATA4,ID1,ID2,ID3,SELECT,SELECT2,OUT1,OUT2,X,Y, CENTER,RADIUS, HASCENTER,rightwristx,rightwristy,
	 CALIBRATE,LButton, RButton,MOVE,
	 
	 //Neff-tool
	 leftwristx,
	 leftwristy,
	 corcentre,
	 colcentre,
	 rknee,
	 lknee,
	 sagcentre,
	 comx,
	 headz,
	 trancentre,
	 colycentre,
	 pelvisy,
	 leftwristxIN,
	 leftwristyIN,
	 corcentreIN,
	 colcentreIN,
	 rkneeIN,
	 lkneeIN,
	 sagcentreIN,
	 comxIN,
	 headzIN,
	 trancentreIN,
	 colycentreIN,
	 pelvisyIN,
	 leftwristxOUT,
	 leftwristyOUT,
	 corcentreOUT,
	 colcentreOUT,
	 rkneeOUT,
	 lkneeOUT,
	 sagcentreOUT,
	 comxOUT,
	 headzOUT,
	 trancentreOUT,
	 colycentreOUT,
	 pelvisyOUT,
	 
	 //Kinect
	 HIP_CENTER,
	 SPINE,
	 SHOULDER_CENTER,
	 HEAD,
	 SHOULDER_LEFT,
	 ELBOW_LEFT,
	 WRIST_LEFT,
	 HAND_LEFT,
	 SHOULDER_RIGHT,
	 ELBOW_RIGHT,
	 WRIST_RIGHT,
	 HAND_RIGHT,
	 HIP_LEFT,
	 KNEE_LEFT,
	 ANKLE_LEFT,
	 FOOT_LEFT,
	 HIP_RIGHT,
	 KNEE_RIGHT,
	 ANKLE_RIGHT,
	 FOOT_RIGHT, RESETMOV, RESETSEL
	 
}
